{ mb, fx, api, lib, ... }:

let
  validateValue = fx.types.validateValue;

  emptyModel = {
    _con = "MetaBuilderDocumentation";
    name = "builder";
    builder = "unspecified";
    inputs = [ ];
    dependencies = [ ];
    tools = [ ];
    outputs = [ ];
    descriptors = [ ];
    evidence = [ ];
    operations = [ ];
    runtimeCapabilities = [ ];
    runtimeProtocols = [ ];
    runtimeServices = [ ];
    materializedUnits = [ ];
  };

  appendOperation = { domain, op, name, summary }: state:
    state // {
      operations = state.operations ++ [{
        _con = "MetaBuilderDocOperation";
        inherit domain name summary;
        constructor = op._con;
      }];
    };

  withOperation = args: update: state:
    appendOperation args (update state);

  sourceSummary = source:
    if source._con == "localSource" then
      "source '${source.name}' from ${toString source.path}"
    else if source._con == "generatedSource" then
      "source '${source.name}' generated by ${source.producer}"
    else
      "source '${source.name}'";

  outputSummary = output:
    "output '${output.name}' at ${output.path} (${output.format})";

  handleBuilder = op: state:
    if op._con == "readSource" then
      withOperation {
        domain = "builder";
        op = op;
        name = op.name;
        summary = sourceSummary op.source;
      }
        (s: s // { inputs = s.inputs ++ [ op.source ]; })
        state
    else if op._con == "resolveDependency" then
      withOperation {
        domain = "builder";
        op = op;
        name = op.dependency.name;
        summary = "resolve ${op.dependency.role} dependency '${op.dependency.name}'";
      }
        (s: s // { dependencies = s.dependencies ++ [ op.dependency ]; })
        state
    else if op._con == "declareTool" then
      withOperation {
        domain = "builder";
        op = op;
        name = op.tool.name;
        summary = "declare tool '${op.tool.name}'";
      }
        (s: s // { tools = s.tools ++ [ op.tool ]; })
        state
    else if op._con == "runTool" then
      appendOperation {
        domain = "builder";
        op = op;
        name = op.name;
        summary = "run '${op.tool.name}' with ${toString (builtins.length op.args)} argument(s)";
      } state
    else if op._con == "writeFile" then
      withOperation {
        domain = "builder";
        op = op;
        name = op.output.name;
        summary = "write ${outputSummary op.output}";
      }
        (s: s // { outputs = s.outputs ++ [ op.output ]; })
        state
    else if op._con == "copyPath" then
      withOperation {
        domain = "builder";
        op = op;
        name = op.output.name;
        summary = "copy ${sourceSummary op.source} to ${op.output.path}";
      }
        (s: s // {
          inputs = s.inputs ++ [ op.source ];
          outputs = s.outputs ++ [ op.output ];
        })
        state
    else if op._con == "transformOutput" then
      withOperation {
        domain = "builder";
        op = op;
        name = op.output.name;
        summary = "transform ${outputSummary op.output}";
      }
        (s: s // { outputs = s.outputs ++ [ op.output ]; })
        state
    else if op._con == "validateValue" then
      appendOperation {
        domain = "builder";
        op = op;
        name = op.validation.name;
        summary = "validate '${op.validation.name}'";
      } state
    else if op._con == "emitDescriptor" then
      withOperation {
        domain = "builder";
        op = op;
        name = op.descriptor.name;
        summary = "emit descriptor '${op.descriptor.name}'";
      }
        (s: s // { descriptors = s.descriptors ++ [ op.descriptor ]; })
        state
    else if op._con == "materializeDerivation" then
      withOperation {
        domain = "builder";
        op = op;
        name = op.name;
        summary = "materialize derivation '${op.name}' with ${op.builder}";
      }
        (s: s // { inherit (op) name builder; })
        state
    else if op._con == "declareEvidence" then
      withOperation {
        domain = "builder";
        op = op;
        name = op.evidence.name;
        summary = "declare evidence '${op.evidence.name}'";
      }
        (s: s // { evidence = s.evidence ++ [ op.evidence ]; })
        state
    else
      throw "metaBuilder.describe: unknown builder operation '${op._con}'";

  handleRuntime = op: state:
    if op._con == "declareCapability" then
      withOperation {
        domain = "runtime";
        op = op;
        name = op.category.name;
        summary = "declare capability category '${op.category.name}'";
      }
        (s: s // { runtimeCapabilities = s.runtimeCapabilities ++ [ op.category ]; })
        state
    else if op._con == "declareProtocol" then
      withOperation {
        domain = "runtime";
        op = op;
        name = op.protocol.name;
        summary = "declare protocol '${op.protocol.name}'";
      }
        (s: s // { runtimeProtocols = s.runtimeProtocols ++ [ op.protocol ]; })
        state
    else if op._con == "declareService" then
      withOperation {
        domain = "runtime";
        op = op;
        name = op.service.name;
        summary = "declare service '${op.service.name}'";
      }
        (s: s // { runtimeServices = s.runtimeServices ++ [ op.service ]; })
        state
    else if op._con == "materializeUnit" then
      withOperation {
        domain = "runtime";
        op = op;
        name = op.name;
        summary = "materialize runtime unit '${op.name}'";
      }
        (s: s // { materializedUnits = s.materializedUnits ++ [ op.name ]; })
        state
    else
      throw "metaBuilder.describe: unknown runtime operation '${op._con}'";

  dispatch = mb.program.dispatchWith {
    label = "describe";
    builder = handleBuilder;
    runtime = handleRuntime;
  };

  bulletSection = title: lines:
    if lines == [ ] then ""
    else ''
      ## ${title}

      ${lib.concatMapStringsSep "\n" (line: "- ${line}") lines}

    '';

  renderMarkdown = model:
    let
      operationLine = op:
        "`${op.domain}.${op.constructor}` `${op.name}` - ${op.summary}";
      serviceLine = svc:
        let protocols = lib.concatStringsSep ", " (map (p: p.name) svc.protocols);
        in "`${svc.name}`" + lib.optionalString (protocols != "") " (${protocols})";
      evidenceLine = e:
        "`${e.name}`"
        + lib.optionalString (e.payload != { }) " - ${builtins.toJSON e.payload}";
    in
    ''
      # ${model.name}

      Builder: `${model.builder}`

      ${bulletSection "Inputs" (map sourceSummary model.inputs)}
      ${bulletSection "Dependencies" (map (d: "`${d.role}:${d.name}`") model.dependencies)}
      ${bulletSection "Tools" (map (t: "`${t.name}`") model.tools)}
      ${bulletSection "Outputs" (map outputSummary model.outputs)}
      ${bulletSection "Descriptors" (map (d: "`${d.name}`") model.descriptors)}
      ${bulletSection "Evidence" (map evidenceLine model.evidence)}
      ${bulletSection "Runtime Services" (map serviceLine model.runtimeServices)}
      ${bulletSection "Materialized Runtime Units" (map (name: "`${name}`") model.materializedUnits)}
      ${bulletSection "Operations" (map operationLine model.operations)}
    '';

  run = program:
    let
      result = mb.program.handle { inherit dispatch program; state = emptyModel; };
      model = result.state;
    in
    {
      inherit model;
      markdown = renderMarkdown model;
      inherit (result) value;
    };

  value = { inherit dispatch run renderMarkdown; };

  tests =
    let
      stubDrv = name: { type = "derivation"; inherit name; outPath = "/nix/store/fake-${name}"; };
      source = mb.operations.localSource { name = "schema"; path = "/tmp/schema.proto"; };
      tool = mb.operations.tool { name = "protoc"; package = stubDrv "protoc"; };
      out = mb.operations.output { name = "cpp"; path = "$out/cpp"; format = "tree"; };
      descriptor = mb.operations.descriptor { name = "idl"; payload = { language = "cpp"; }; };
      selfTest = mb.operations.evidence { name = "self-test"; payload = { command = "./run-checks"; }; };
      builderProgram = mb.program.sequence [
        (mb.operations.readSource { name = "schema"; inherit source; })
        (mb.operations.resolveDependency {
          dependency = mb.operations.dependency {
            name = "protobuf";
            role = "native";
            package = stubDrv "protobuf";
          };
        })
        (mb.operations.declareTool { inherit tool; })
        (mb.operations.runTool { name = "generate"; inherit tool; args = [ "--cpp_out=$out/cpp" ]; })
        (mb.operations.transformOutput { output = out; })
        (mb.operations.emitDescriptor { inherit descriptor; })
        (mb.operations.materializeDerivation { name = "idl-generated"; })
        (mb.operations.declareEvidence { evidence = selfTest; })
      ];
      lifecycleCat = mb.operations.capabilityCategory {
        name = "lifecycle";
        capabilities = [ (mb.operations.capability { name = "start"; }) ];
      };
      lifecycleSet = mb.operations.capabilitySet { categories = [ lifecycleCat ]; };
      grpc = mb.operations.protocol {
        name = "grpc";
        transport = mb.operations.transports.TCP;
        serialization = mb.operations.serializations.Protobuf;
        capabilities = lifecycleSet;
      };
      svc = mb.operations.service {
        name = "api";
        package = stubDrv "api";
        capabilities = lifecycleSet;
        protocols = [ grpc ];
      };
      runtimeProgram = mb.program.sequence [
        (mb.operations.declareCapability { category = lifecycleCat; })
        (mb.operations.declareProtocol { protocol = grpc; })
        (mb.operations.declareService { service = svc; })
        (mb.operations.materializeUnit { name = "api"; })
      ];
    in
    {
      "model-validates" = {
        expr = validateValue [ ] mb.descriptions.BuilderDocumentation.T (run builderProgram).model;
        expected = [ ];
      };
      "collects-builder-facts" = {
        expr =
          let model = (run builderProgram).model;
          in {
            inherit (model) name builder;
            inputCount = builtins.length model.inputs;
            dependencyCount = builtins.length model.dependencies;
            toolCount = builtins.length model.tools;
            outputCount = builtins.length model.outputs;
            descriptorCount = builtins.length model.descriptors;
            evidenceCount = builtins.length model.evidence;
            operationCount = builtins.length model.operations;
          };
        expected = {
          name = "idl-generated";
          builder = "runCommand";
          inputCount = 1;
          dependencyCount = 1;
          toolCount = 1;
          outputCount = 1;
          descriptorCount = 1;
          evidenceCount = 1;
          operationCount = 8;
        };
      };
      "collects-runtime-facts" = {
        expr =
          let model = (run runtimeProgram).model;
          in {
            capabilityCount = builtins.length model.runtimeCapabilities;
            protocolCount = builtins.length model.runtimeProtocols;
            serviceCount = builtins.length model.runtimeServices;
            unitCount = builtins.length model.materializedUnits;
            serviceName = (builtins.head model.runtimeServices).name;
          };
        expected = {
          capabilityCount = 1;
          protocolCount = 1;
          serviceCount = 1;
          unitCount = 1;
          serviceName = "api";
        };
      };
      "markdown-renders-model" = {
        expr =
          let md = (run builderProgram).markdown;
          in lib.hasInfix "# idl-generated" md
            && lib.hasInfix "protoc" md
            && lib.hasInfix "emitDescriptor" md
            && lib.hasInfix "## Evidence" md
            && lib.hasInfix "`self-test` - " md;
        expected = true;
      };

      "markdown-omits-evidence-section-when-empty" = {
        expr = lib.hasInfix "## Evidence" (run runtimeProgram).markdown;
        expected = false;
      };
    };
in
{
  scope = {
    describe = api.mk {
      description = "describe: interprets builder programs into a typed self-documentation model.";
      doc = ''
        Builds a documentation model from the builder's own operation program.
        This is distinct from `mkDocsContent`, which documents metaBuilder's
        public API.
      '';
      inherit value;
    };
  };
  tests = lib.mapAttrs'
    (name: test: {
      name = "describe-${name}";
      value = test;
    })
    tests;
}
