{ mb, api, lib, ... }:

let
  line = text: "- ${text}";

  sourceLabel = source:
    if source._con == "localSource" then "${source.name} (${toString source.path})"
    else if source._con == "generatedSource" then "${source.name} (generated by ${source.producer})"
    else source.name;

  outputLabel = output:
    "${output.name} -> ${output.path} (${output.format})";

  enumLabel = value: value._con or (toString value);

  capabilityNames = capSet:
    let
      fromCategories = builtins.concatMap
        (category: map (capability: capability.name) category.capabilities)
        capSet.categories;
      fromCustom = map (capability: capability.name) capSet.custom;
    in
    fromCategories ++ fromCustom;

  protocolLabel = protocol:
    let
      endpoint =
        if protocol.defaultPort != null && protocol.portEnvVar != null then
          " ${protocol.portEnvVar}:${toString protocol.defaultPort}"
        else if protocol.defaultPort != null then
          " port ${toString protocol.defaultPort}"
        else if protocol.portEnvVar != null then
          " ${protocol.portEnvVar}"
        else "";
    in
    "${protocol.name}/${enumLabel protocol.transport}/${enumLabel protocol.serialization}${endpoint}";

  serviceLabel = service:
    let
      protocols = map protocolLabel service.protocols;
      capabilities = capabilityNames service.capabilities;
      protocolText =
        if protocols == [ ] then "no protocols"
        else lib.concatStringsSep ", " (map (p: "`${p}`") protocols);
      capabilityText =
        if capabilities == [ ] then "no capabilities"
        else lib.concatStringsSep ", " (map (c: "`${c}`") capabilities);
    in
    "service `${service.name}` exposes ${protocolText}; capabilities ${capabilityText}";

  descriptorLabel = descriptor:
    let
      keys = builtins.attrNames descriptor.payload;
      keyText =
        if keys == [ ] then "no payload keys"
        else "payload keys " + lib.concatStringsSep ", " (map (k: "`${k}`") keys);
    in
    "descriptor `${descriptor.name}` (${keyText})";

  diagnosticLabel = diagnostic:
    let
      severity = diagnostic.severity or "diagnostic";
      code = diagnostic.code or "unknown";
      message = diagnostic.message or "";
    in
    "${severity}:${code}" + lib.optionalString (message != "") " ${message}";

  dryStepLabel = step:
    if step.kind == "source" then "source `${step.name}`"
    else if step.kind == "dependency" then "dependency `${step.role}:${step.name}`"
    else if step.kind == "tool" then "tool `${step.name}`"
    else if step.kind == "run" then "run `${step.name}` with `${step.tool}`"
    else if step.kind == "write" then "write `${step.path}`"
    else if step.kind == "copy" then "copy to `${step.to}`"
    else if step.kind == "transform" then "transform `${step.name}` (${step.format})"
    else if step.kind == "validate" then "validate `${step.name}`"
    else if step.kind == "descriptor" then "descriptor `${step.name}`"
    else if step.kind == "evidence" then "evidence `${step.name}`"
    else if step.kind == "materialize" then "materialize `${step.name}` with `${step.builder}`"
    else if step.kind == "declare-capability" then "runtime capability `${step.name}`"
    else if step.kind == "declare-protocol" then "runtime protocol `${step.name}`"
    else if step.kind == "declare-service" then "runtime service `${step.name}`"
    else if step.kind == "materialize-unit" then "runtime unit `${step.name}`"
    else step.kind;

  isRuntimeStep = step:
    builtins.elem step.kind [
      "declare-capability"
      "declare-protocol"
      "declare-service"
      "materialize-unit"
    ];

  planStepLabel = step:
    if step.con == "runStep" then "run `${step.name}`"
    else if step.con == "writeStep" then "write `${step.name}`"
    else if step.con == "copyStep" then "copy `${step.name}`"
    else step.name;

  depNodeSummary = node: {
    inherit (node) id name role;
  } // lib.optionalAttrs (node ? tool) {
    inherit (node) tool;
  } // lib.optionalAttrs (node ? packageName) {
    inherit (node) packageName;
  } // lib.optionalAttrs (node ? packageOutPath && node.packageOutPath != null) {
    inherit (node) packageOutPath;
  };

  depNodeLine = node:
    let
      packageText =
        if node ? packageName then " package `${node.packageName}`" else "";
      toolText =
        if node ? tool then " via `${node.tool}`" else "";
    in
    "node `${node.id}` (${node.role})${toolText}${packageText}";

  depEdgeLine = edge:
    "edge `${edge.from}` -> `${edge.to}` (${edge.kind})";

  planShellStepLine = pathMap: step:
    let snippet = firstLines 1 (sanitizeShell pathMap step.shell);
    in "`${step.name}`: `${snippet}`";

  artifactLine = artifact:
    "${artifact.kind} `${artifact.name}`";

  renderList = title: items:
    if items == [ ] then ''
      ### ${title}

      None.

    ''
    else ''
      ### ${title}

      ${lib.concatMapStringsSep "\n" line items}

    '';

  firstLines = n: text:
    let lines = lib.take n (lib.splitString "\n" text);
    in lib.concatStringsSep "\n" lines;

  sanitizeShellLine = pathMap: line:
    if !(lib.hasPrefix "pathMap_" line) then line
    else
      let
        parts = lib.splitString "=" line;
        key = builtins.unsafeDiscardStringContext
          (if parts == [ ] then "" else builtins.head parts);
        source = pathMap.${key} or null;
      in
      if source != null then "${key}=<source:${baseNameOf source}>"
      else line;

  sanitizeShell = pathMap: shell:
    lib.concatStringsSep "\n"
      (map (sanitizeShellLine pathMap) (lib.splitString "\n" shell));

  renderMarkdown = view:
    let
      validationLine =
        if view.validation.ok then "ok"
        else "${toString view.validation.diagnosticCount} diagnostic(s)";
      shellExcerpt =
        if view.plan.shellExcerpt == "" then ""
        else ''
          ### Plan Shell Excerpt

          ```sh
          ${view.plan.shellExcerpt}
          ```

        '';
    in
    ''
      The same internalized program is interpreted several ways.

      ${renderList "Validation" ([
        "result: `${validationLine}`"
      ] ++ view.validation.diagnosticLines)}${renderList "Dependency Graph" ([
        "nodes: `${toString view.dependencies.nodeCount}`"
        "edges: `${toString view.dependencies.edgeCount}`"
        "services: `${toString view.dependencies.serviceCount}`"
      ] ++ view.dependencies.lines)}${renderList "Dry Run - Builder" view.dryRun.builderLines}${renderList "Dry Run - Runtime" view.dryRun.runtimeLines}${renderList "Plan View" (view.plan.stepLines ++ view.plan.shellStepLines)}${shellExcerpt}${renderList "Runtime Services" view.documentation.runtimeServiceLines}${renderList "Descriptors" view.documentation.descriptorLines}${renderList "Builder Self-Documentation" [
        "documented operations: `${toString view.documentation.operationCount}`"
        "runtime services: `${toString view.documentation.runtimeServiceCount}`"
      ]}${renderList "Materialized Outputs" view.materialization.outputLines}${renderList "Materialization" ([
        "derivation: `${view.materialization.derivationName}`"
        "outputs: `${toString view.materialization.outputCount}`"
        "runtime artifacts: `${toString view.materialization.runtimeArtifactCount}`"
      ] ++ view.materialization.runtimeArtifactLines)}${renderList "Substrates" view.substrates.lines}
    '';

  run = program:
    let
      validation = mb.program.validate.run program;
      deps = mb.program.deps.run program;
      dryRun = mb.program."dry-run".run program;
      materialize = mb.program.materialize.run program;
      planView = mb.program."plan-view".fromMaterialize materialize;
      docs = mb.program.describe.run program;

      dependencyNodes = map depNodeSummary deps.nodes;
      dependencyEdges = map
        (edge: {
          inherit (edge) from to kind;
        })
        deps.edges;
      dependencyLines =
        (map depNodeLine dependencyNodes)
        ++ (map depEdgeLine dependencyEdges);
      dryStepLines = map dryStepLabel dryRun.steps;
      dryBuilderLines = map dryStepLabel (lib.filter (step: !(isRuntimeStep step)) dryRun.steps);
      dryRuntimeLines = map dryStepLabel (lib.filter isRuntimeStep dryRun.steps);
      planStepLines = map planStepLabel planView.steps;
      planShellStepLines = map (planShellStepLine planView.pathMap) planView.steps;
      runtimeServiceLines = map serviceLabel docs.model.runtimeServices;
      descriptorLines = map descriptorLabel docs.model.descriptors;
      materializationOutputLines = map outputLabel materialize.plan.outputs;
      runtimeArtifactLines = map artifactLine materialize.plan.runtimeArtifacts;

      substrateView = backend:
        let reasons = backend.unsupportedReasons materialize.plan;
        in { supported = reasons == [ ]; inherit reasons; };
      substrates = {
        shell = substrateView mb.program.backends.shell;
        dockerfile = substrateView mb.program.backends.dockerfile;
      };
      substrateLines = lib.mapAttrsToList
        (name: sub:
          if sub.supported then "${name}: `supported`"
          else "${name}: unsupported (${lib.concatStringsSep "; " sub.reasons})")
        substrates;

      view = {
        validation = {
          inherit (validation) ok diagnostics;
          diagnosticCount = builtins.length validation.diagnostics;
          diagnosticLines = map diagnosticLabel validation.diagnostics;
        };
        dependencies = {
          nodes = dependencyNodes;
          edges = dependencyEdges;
          lines = dependencyLines;
          nodeCount = builtins.length dependencyNodes;
          edgeCount = builtins.length dependencyEdges;
          serviceCount = builtins.length (builtins.attrNames deps.services);
        };
        dryRun = {
          steps = dryRun.steps;
          stepLines = dryStepLines;
          builderLines = dryBuilderLines;
          runtimeLines = dryRuntimeLines;
          stepCount = builtins.length dryRun.steps;
        };
        plan = {
          inherit (planView) name builder shell;
          stepLines = planStepLines;
          shellStepLines = planShellStepLines;
          stepCount = builtins.length planView.steps;
          toolNames = map (tool: tool.name) planView.tools;
          outputs = map outputLabel planView.outputs;
          outputCount = builtins.length planView.outputs;
          pathMapCount = builtins.length (builtins.attrNames planView.pathMap);
          shellExcerpt = firstLines 10 (sanitizeShell planView.pathMap planView.shell);
        };
        documentation = {
          inherit (docs) markdown;
          inherit (docs.model) name builder;
          operationCount = builtins.length docs.model.operations;
          inputLines = map sourceLabel docs.model.inputs;
          outputLines = map outputLabel docs.model.outputs;
          descriptorLines = descriptorLines;
          runtimeServiceCount = builtins.length docs.model.runtimeServices;
          runtimeServiceLines = runtimeServiceLines;
          materializedUnits = docs.model.materializedUnits;
        };
        materialization = {
          inherit (materialize.plan) name builder;
          derivationName = materialize.derivation.name;
          outputLines = materializationOutputLines;
          outputCount = builtins.length materialize.plan.outputs;
          runtimeArtifactCount = builtins.length materialize.plan.runtimeArtifacts;
          runtimeArtifacts = map
            (artifact: {
              inherit (artifact) kind name;
            })
            materialize.plan.runtimeArtifacts;
          runtimeArtifactLines = runtimeArtifactLines;
        };
        substrates = substrates // { lines = substrateLines; };
      };
    in
    view // {
      markdown = renderMarkdown view;
    };

  tests =
    let
      stubDrv = name: { type = "derivation"; inherit name; outPath = "/nix/store/fake-${name}"; };
      source = mb.operations.localSource { name = "schema"; path = "/tmp/schema.proto"; };
      tool = mb.operations.tool { name = "protoc"; package = stubDrv "protoc"; };
      program = mb.program.sequence [
        (mb.operations.readSource { name = "schema"; inherit source; })
        (mb.operations.declareTool { inherit tool; })
        (mb.operations.runTool {
          name = "generate";
          inherit tool;
          args = [ "--cpp_out=$out/cpp" (toString source.path) ];
        })
        (mb.operations.transformOutput {
          output = mb.operations.output {
            name = "cpp";
            path = "$out/cpp";
            format = "tree";
          };
        })
        (mb.operations.emitDescriptor {
          descriptor = mb.operations.descriptor {
            name = "metadata";
            payload = { language = "cpp"; };
          };
        })
        (mb.operations.materializeDerivation { name = "generated"; })
      ];
      lifecycleCat = mb.operations.capabilityCategory {
        name = "lifecycle";
        capabilities = [ (mb.operations.capability { name = "start"; }) ];
      };
      lifecycleSet = mb.operations.capabilitySet { categories = [ lifecycleCat ]; };
      svc = mb.operations.service {
        name = "api";
        package = stubDrv "api";
        capabilities = lifecycleSet;
      };
      runtimeProgram = mb.program.sequence [
        (mb.operations.declareCapability { category = lifecycleCat; })
        (mb.operations.declareService { service = svc; })
        (mb.operations.materializeUnit { name = "api"; })
      ];
    in
    {
      "composes-core-views" = {
        expr =
          let view = run program;
          in {
            validationOk = view.validation.ok;
            dependencyNodes = view.dependencies.nodeCount;
            dependencyLines = view.dependencies.lines;
            dryBuilderSteps = view.dryRun.builderLines;
            dryRuntimeSteps = view.dryRun.runtimeLines;
            dryRunSteps = view.dryRun.stepCount;
            planSteps = view.plan.stepCount;
            planShellStepCount = builtins.length view.plan.shellStepLines;
            planShellHasPathMap = lib.hasInfix "$pathMap_" (builtins.head view.plan.shellStepLines);
            docOps = view.documentation.operationCount;
            descriptors = view.documentation.descriptorLines;
            outputs = view.materialization.outputLines;
            drvName = view.materialization.derivationName;
          };
        expected = {
          validationOk = true;
          dependencyNodes = 2;
          dependencyLines = [
            "node `tool:protoc` (tool) package `protoc`"
            "node `operation:generate` (operation) via `protoc`"
            "edge `tool:protoc` -> `operation:generate` (uses-tool)"
          ];
          dryBuilderSteps = [
            "source `schema`"
            "tool `protoc`"
            "run `generate` with `protoc`"
            "transform `cpp` (tree)"
            "descriptor `metadata`"
            "materialize `generated` with `runCommand`"
          ];
          dryRuntimeSteps = [ ];
          dryRunSteps = 6;
          planSteps = 1;
          planShellStepCount = 1;
          planShellHasPathMap = true;
          docOps = 6;
          descriptors = [ "descriptor `metadata` (payload keys `language`)" ];
          outputs = [ "cpp -> $out/cpp (tree)" ];
          drvName = "generated";
        };
      };

      "markdown-names-one-build-many-views" = {
        expr =
          let markdown = (run runtimeProgram).markdown;
          in {
            hasIntro = lib.hasInfix "same internalized program" markdown;
            hasValidation = lib.hasInfix "### Validation" markdown;
            hasRuntimeServices = lib.hasInfix "### Runtime Services" markdown;
            hasRuntimeArtifacts = lib.hasInfix "runtime artifacts" markdown;
          };
        expected = {
          hasIntro = true;
          hasValidation = true;
          hasRuntimeServices = true;
          hasRuntimeArtifacts = true;
        };
      };

      "substrates-declare-support" = {
        expr =
          let view = run program;
          in {
            shellSupported = view.substrates.shell.supported;
            dockerfileSupported = view.substrates.dockerfile.supported;
            markdownHasSection = lib.hasInfix "### Substrates" view.markdown;
          };
        expected = {
          shellSupported = true;
          dockerfileSupported = true;
          markdownHasSection = true;
        };
      };

      "substrates-surface-unsupported-reasons" = {
        expr =
          let
            view = run (mb.program.sequence [
              (mb.operations.resolveDependency {
                dependency = mb.operations.dependency {
                  name = "zlib";
                  role = "native";
                  package = stubDrv "zlib";
                };
              })
            ]);
          in
          {
            shellSupported = view.substrates.shell.supported;
            dockerfileSupported = view.substrates.dockerfile.supported;
            hasReason = builtins.length view.substrates.dockerfile.reasons > 0;
          };
        expected = {
          shellSupported = true;
          dockerfileSupported = false;
          hasReason = true;
        };
      };

      "shell-excerpt-redacts-pathmap-values" = {
        expr =
          let view = run program;
          in {
            hasSourceLabel = lib.hasInfix "<source:schema.proto>" view.plan.shellExcerpt;
            leaksTmp = lib.hasInfix "/tmp/schema.proto" view.plan.shellExcerpt;
          };
        expected = {
          hasSourceLabel = true;
          leaksTmp = false;
        };
      };
    };

  value = { inherit run renderMarkdown; };
in
{
  scope = {
    introspect = api.mk {
      description = "introspect: composed builder self-view over validation, deps, dry-run, plan-view, describe, and materialize.";
      doc = ''
        `introspect.run program` returns every standard view of one builder
        program — validation, dependencies, dry-run, plan, documentation,
        materialization, substrate support — plus a rendered markdown
        summary.
      '';
      inherit value;
    };
  };
  tests = lib.mapAttrs'
    (name: test: {
      name = "introspect-${name}";
      value = test;
    })
    tests;
}
